### ISSUE TITLE
Toggle per scene

### ISSUE THREAD

**Issue by eiqnepm** [EZ64cool/obs-hadowplay#1]
Nice plugin, very convenient!

Would be nice if I was able to enable and disable this plugin based on which scene collection is selected, or even an option in the properties of the game capture source itself.

**Comment by EZ64cool** [comment]
Yep, definitely agree.
I'll aim to do a settings pass

**Comment by EZ64cool** [comment]
Something similar should now be avaliable in [1.1.4-beta](https://github.com/EZ64cool/obs-hadowplay/releases/tag/1.1.4-beta) for testing.
Unfortunatley I ended up going with settings being at the Scene Collection level instead of per scene.
