### ISSUE TITLE
Not seeing any options in the tool tab.

### ISSUE THREAD

**Issue by RicardsR** [EZ64cool/obs-hadowplay#15]
Not seeing any options in the tool tab after installing the plugin on OBS Studio version 30.1.1. Could it be that the plugin is just outdated for now so its just not showing up? (OS: Windows 11)

**Comment by EZ64cool** [comment]
Hey, I haven't released 1.1.4 out of beta yet (I still want to do some clean up but haven't had the time) so it doesn't show up as the default download.
But I've been using it and it's been stable https://github.com/EZ64cool/obs-hadowplay/releases/tag/1.1.4-beta

**Comment by RicardsR** [comment]
Yep, installed the 1.1.4 version and everything seems to be working. Thank you for the plugin and for the amazing quick response!
