### ISSUE TITLE
Automatic targeting issue and no auto replay buffer start.

### ISSUE THREAD

**Issue by RicardsR** [EZ64cool/obs-hadowplay#16]
After installing the 1.1.4 beta build, seems like it isn't able to start and stop the replay buffer on its own and I have to do it manually.
As well as, when the replay buffer is automatically started, it is able to find the first target of the game just fine and saves the clips in the correct directory. But if I exit out of the game it never realizes that the game is closed and even when switching to a different game, it still thinks its in the first game it detected when the replay buffer was first turned on and never updates to the new application name.

I've attached my log file so you can see better what I'm talking about. It shows the game capture and the plugin itself finding Terraria just fine, but after switching to Stardew Valley, the game capture itself sees it but the plugin doesn't and so, the plugin still thinks it's Terraria. (Lines 274 -> 302).
On line 126 the plugin does say that it was loaded successfully.

[2024-03-25 13-19-38.txt](https://github.com/EZ64cool/obs-hadowplay/files/14742788/2024-03-25.13-19-38.txt)

**Comment by EZ64cool** [comment]
Hmm, the plugin not being able to start on it's own is definitely the main cause for this issue. The way it currently works is that the app name is grabbed at replay start. This works for the automatic replay since it starts/stops between programs. However a manual start will never update it's app name.

In terms of fixing the automatic replay buffer, can you check all your current settings for obs_hadowplay under the tools menu?

I should be able to update the behaviour for manual replay start to grab the current fullscreen app instead of the app at start.

**Comment by RicardsR** [comment]
Settings wise I both tried with the default settings that you get at the start and having the windows notifications off (since I don't need that) and both cases caused the same issue. I did try to untick and retick the auto replay start option but nothing changed.
But yeah, starting manually the replay buffer caused the plugin to wake up and register the current captured instance. Every time the clip was saved though, the sound effect did play so I guess it does recognise the instance itself, just doesn't update it.

**Comment by RicardsR** [comment]
Yep, both games were full screen. I also tried out Team Fortress 2 and Hunt Showdown and had the same issue.
If you want you can add me on discord and I can help out with the trouble shooting so it's easier.
Discord: https://discord.com/invite/Ru6N9X2Z

**Comment by EZ64cool** [comment]
Ahhhhh, I just figured it out.
It looks like you're using a scene reference that has a game_capture inside it, currently I haven't accounted for that, but it should be fairly easy to fix.
I can get that sorted and into the next version

**Comment by EZ64cool** [comment]
Awesome, this should now be fixed in https://github.com/EZ64cool/obs-hadowplay/releases/tag/1.2.1-beta
Thanks for finding this and posting your logs, always appreciated 🥇
