### ISSUE TITLE
Game title broken in 2.0.1

### ISSUE THREAD

**Issue by WatislavB** [EZ64cool/obs-hadowplay#30]
In 2.0.1, the folder name for Valorant began to look like this: 

![image](https://github.com/EZ64cool/obs-hadowplay/assets/91764346/5e2182f0-b4c8-439a-a4e5-72bb0b50c9b7)

**Comment by EZ64cool** [comment]
Ahh, thanks for spotting this.

I managed to find it and it's such a small silly bug 😭
