### ISSUE TITLE
Replay is not moved to its game folder

### ISSUE THREAD

**Issue by Just-Xt** [EZ64cool/obs-hadowplay#34]
The feature seems to work on all games I've tried except CoD MWiii. 

Looking at the logs, there's a space after the program name : 

> 01:30:51.073: [obs-hadowplay] Renaming files: C:/Users/XXX/Videos/Replay_2024-07-06_01-30-51.mp4 -> C:/Users/XXX/Videos/Call of Duty® HQ /Replay_2024-07-06_01-30-51.mp4

> "Call of Duty® HQ "

 My guess is that since folder names can't have a trailing space, Windows trims it when the folder is created and then hadowplay doesn't know where to move the file.

**Comment by EZ64cool** [comment]
Hey, this should be fixed the in latest release (2.0.3)

**Comment by Just-Xt** [comment]
It works, thanks!
