### ISSUE TITLE
Adding exceptions

### ISSUE THREAD

**Issue by scorthyn** [EZ64cool/obs-hadowplay#5]
Hey, is it possible to prevent hadowplay to automatically capture my vlc player \ video player when fullscreen? Some kind of blacklist

**Comment by EZ64cool** [comment]
Ah definitely, I already have an exception list setup. Looks like I missed VLC but I'll add it in :)
https://github.com/EZ64cool/obs-hadowplay/blob/3e313f7fdb8e13341cd1915c9543a5ad57dd7584/src/plugin-windows.c#L140C25-L140C25

**Comment by scorthyn** [comment]
oh nice, is it included? Also if I want to edit that i just need to write the name of the process? like Potplayer for example I also use

**Comment by EZ64cool** [comment]
Yeah exactly, I'd probably like to allow users to add/edit this list in settings somehow. But for now it's just a static list.

**Comment by scorthyn** [comment]
Can you add VLC and Potplayer and send me the file i need to replace? would be perfect

**Comment by EZ64cool** [comment]
For now I had to release a new version to add this, which I'll do today. I'll add both VLC and Potplayer for now, but in the future I'll add a proper file on disk that users can add to.

**Comment by scorthyn** [comment]
Awesome :D , this basically replaced the bloatware from Nvidia

**Comment by EZ64cool** [comment]
Something I've sadly realised is that this exception list currently only applies to the reorganisation of files.
In order to stop the replay buffer from starting will require a bit more work. Ideally in the future I'll be able to grab the name of the exe the game_capture is attached to, but currently I have to guess based on the current topmost fullscreen application.

**Comment by scorthyn** [comment]
> Something I've sadly realised is that this exception list currently only applies to the reorganisation of files. In order to stop the replay buffer from starting will require a bit more work. Ideally in the future I'll be able to grab the name of the exe the game_capture is attached to, but currently I have to guess based on the current topmost fullscreen application.

Version 1.13 is good and everything is working. The exception list yeah still captures my potplayer but one thing I noticed is that it stops the replay buffer and stops capturing it when I exit the player. That wasn't the case before. Thanks for the work and can't wait for new versions!

**Comment by scorthyn** [comment]
Sorry to bother again, any news on the exceptions :D? If not possible to make the user select what not to record just add these that seems to be capturing on my side:

- Potplayer
- Stremio
- Vlc

Any kind of video player who uses HW acceleration obs will pick it up.

**Comment by EZ64cool** [comment]
I have actually had some success with this in testing. But I don't want to push it out until I've got the ability for users to manually assign their own exceptions.

This still probably start off as a file and eventually when settings are added through they instead.

So hopefully this should be available soon-ish

**Comment by scorthyn** [comment]
> I have actually had some success with this in testing. But I don't want to push it out until I've got the ability for users to manually assign their own exceptions.
> 
> This still probably start off as a file and eventually when settings are added through they instead.
> 
> So hopefully this should be available soon-ish

I can test it for you even tho there's no manual exceptions :) send me link for the "beta" ;)

**Comment by EZ64cool** [comment]
This should now be avaliable in [1.1.4-beta](https://github.com/EZ64cool/obs-hadowplay/releases/tag/1.1.4-beta) for testing.
