### ISSUE TITLE
1.2 crashes when capturing

### ISSUE THREAD

**Issue by scorthyn** [EZ64cool/obs-hadowplay#7]
Here's the log file - https://justpaste.it/9c2v8
Crash report - https://justpaste.it/80823

Its on a clean installation. Tested 1.1 and it works fine.
Also, can you publish a .zip version like in 1.1 version? i don't want to "install it". Thanks for your work!

**Comment by EZ64cool** [comment]
Ooh, thanks for the detailed report. I'll look into both of these things :)

**Comment by EZ64cool** [comment]
This should now be fixed, the new release should also contain a .zip for windows
I've also swapped over to RelWithDebInfo which will inlcude the pdb, meaning any future crashes should be a lot easier to track down.
